sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
#    access-key-id: 你的ALIYUN_OSS_ACCESS_KEY_ID
#    access-key-secret: 你的ALIYUN_OSS_ACCESS_KEY_SECRET
    bucket-name: sky-take-out-cxl